travis:
  secure:
    BINSTAR_TOKEN: GbyUKs0PUGPzFgxB5xI/xqsB2uSD75Q1H+JpVoPeURQRthFnw5g/17UHZFSVwGc+3cyGmW9XXO4ZBOKdB5HxTn2Sl0TY4quRpYowLCK6XKC0rw8A55LNxGSxFP8c4HR+1m/1qdZJ9Xrz9zTTLPFYXCIf3ywufz99A38wkwu7Y8GqmiqGSkNJH42hmKSHtknaMPL/xbEP7oMUoH2vcZdT10xEhEdRDEgdTkV9vmd/5Aszd799heg8ga2lhcr7QNgTDwg4wpyZ8yvk/U5nbGHpZm/No7mrtPfkIyWPmT1j1ptmcSK9mAXrdL6sa4DY/v7sSV2rsrGBayaXEh//Drb11g6yvHCpoCmb0oI9X0MTpgwWnZRgjXy8MgLTRfAvATA5x1aQ7gGwNUpR41eq48vLIX2h2rW31kg+U6zMhlzEPgN+sgBXu3Tw/7KQal8MtuOhamn+hL0QjgTUpmuifdZ8uuKXeKPaJ3PQYBF+sr4D41k0SrxO5Q+kY8DhLb6PSHOk4Wq0XU+SaA/6DswvqC0Pnl+sLdKX9A5wWruejBo0EUst2DdDwE6suGaBsIcy4JqrDA2S+SBwAMisxlz323AoRQfL6rhMLZei3UnXTbYodf1rQxi1s0WwY7Y6jfIFMsMGc/j5ho/kw7e9l/NJu53S/Qqm7F9WmMHvXNVXyXxA14Y=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
- osx_64
conda_build:
  pkg_format: '2'
